"""GIX Career Event Eligibility Checker — generated by Cursor with .cursorrules."""

from dataclasses import dataclass
from datetime import date

import streamlit as st

st.set_page_config(page_title="GIX Eligibility Checker", page_icon="🎓", layout="centered")

RECOGNIZED_PROGRAMS = {"MSTI", "MDE", "MBA", "EMBA"}

QUARTER_MONTH_MAP = {
    "Win": 1,
    "Spr": 4,
    "Sum": 7,
    "Aut": 10,
}


@dataclass
class EventEligibility:
    """Eligibility result for a single career event."""

    event: str
    eligible: bool
    reason: str


def parse_graduation_quarter(quarter_str: str) -> date | None:
    """Parse a graduation quarter string into an approximate date.

    Args:
        quarter_str: String in format "Win 2025", "Spr 2025", etc.

    Returns:
        A date object representing the start of that quarter, or None if unparseable.
    """
    parts = quarter_str.strip().split()
    if len(parts) != 2:
        return None
    season, year_str = parts
    if season not in QUARTER_MONTH_MAP:
        return None
    try:
        year = int(year_str)
    except ValueError:
        return None
    return date(year, QUARTER_MONTH_MAP[season], 1)


def compute_eligibility(
    program: str,
    graduation_date: date | None,
    cpt_status: str,
) -> list[EventEligibility]:
    """Compute eligibility for each career event.

    Args:
        program: Student's program name.
        graduation_date: Parsed graduation date, or None if unparseable.
        cpt_status: One of "Active", "Inactive", "Not Applicable".

    Returns:
        A list of EventEligibility results, one per event.
    """
    today = date.today()
    recognized = program in RECOGNIZED_PROGRAMS

    if graduation_date is not None:
        months_until_grad = (graduation_date.year - today.year) * 12 + (
            graduation_date.month - today.month
        )
        within_four_quarters = 0 <= months_until_grad <= 12
    else:
        within_four_quarters = False

    return [
        EventEligibility(
            event="Mock Interviews",
            eligible=recognized,
            reason="Open to all recognized programs." if recognized else "Program not recognized.",
        ),
        EventEligibility(
            event="Resume Reviews",
            eligible=recognized,
            reason="Open to all recognized programs." if recognized else "Program not recognized.",
        ),
        EventEligibility(
            event="Employer Panels",
            eligible=recognized and within_four_quarters,
            reason=(
                "Eligible — graduating within 4 quarters."
                if recognized and within_four_quarters
                else "Requires recognized program and graduation within 4 quarters."
            ),
        ),
        EventEligibility(
            event="Networking Nights",
            eligible=True,
            reason="Open to all students regardless of program or status.",
        ),
        EventEligibility(
            event="CPT Info Sessions",
            eligible=cpt_status == "Active",
            reason=(
                "Eligible — Active CPT status." if cpt_status == "Active" else "Requires Active CPT status."
            ),
        ),
    ]


# ── UI ────────────────────────────────────────────────────────────────────────

st.title("GIX Career Event Eligibility Checker")
st.caption("Find out which career events you qualify for.")

program = st.selectbox("Program", ["MSTI", "MDE", "MBA", "EMBA", "Other"])
graduation_quarter = st.text_input("Graduation Quarter", placeholder="e.g. Spr 2026")
cpt_status = st.radio("CPT Status", ["Active", "Inactive", "Not Applicable"])

if not graduation_quarter.strip():
    st.info("Please enter your graduation quarter to see results.")
    st.stop()

graduation_date = parse_graduation_quarter(graduation_quarter)

if program == "Other" or graduation_date is None:
    st.warning(
        "Your situation may require advisor review. "
        "Please contact GIX Career Services directly."
    )
    st.stop()

results = compute_eligibility(program, graduation_date, cpt_status)

import pandas as pd

df = pd.DataFrame(
    {
        "Event": [r.event for r in results],
        "Eligible": ["Yes" if r.eligible else "No" for r in results],
        "Reason": [r.reason for r in results],
    }
)


def highlight_eligibility(val: str) -> str:
    """Apply green/red background to eligibility column."""
    if val == "Yes":
        return "background-color: #d4edda; color: #155724"
    return "background-color: #f8d7da; color: #721c24"


styled = df.style.map(highlight_eligibility, subset=["Eligible"])
st.dataframe(styled, use_container_width=True, hide_index=True)
