"""GIX Career Event Eligibility Checker — generated by ChatGPT (GPT-4o), no config file."""

import streamlit as st
from datetime import date

st.title("GIX Career Event Eligibility Checker")

RECOGNIZED_PROGRAMS = ["MSTI", "MDE", "MBA", "EMBA"]

QUARTER_MAP = {"Win": 1, "Spr": 4, "Sum": 7, "Aut": 10}

program = st.selectbox("Program", ["MSTI", "MDE", "MBA", "EMBA", "Other"])
graduation_quarter = st.text_input("Graduation Quarter (e.g. Spr 2025)")
cpt_status = st.radio("CPT Status", ["Active", "Inactive", "Not Applicable"])

if st.button("Check Eligibility"):
    if program == "Other":
        st.warning("Your situation may require advisor review. Contact GIX Career Services.")
    else:
        parts = graduation_quarter.split()
        season = parts[0]
        year = int(parts[1])
        month = QUARTER_MAP[season]
        grad_date = date(year, month, 1)
        today = date.today()
        months_away = (grad_date.year - today.year) * 12 + (grad_date.month - today.month)
        within_4q = 0 <= months_away <= 12

        results = [
            {"Event": "Mock Interviews", "Eligible": "Yes", "Reason": "Open to all programs"},
            {"Event": "Resume Reviews", "Eligible": "Yes", "Reason": "Open to all programs"},
            {
                "Event": "Employer Panels",
                "Eligible": "Yes" if within_4q else "No",
                "Reason": "Within 4Q" if within_4q else "Not within 4 quarters of graduation",
            },
            {"Event": "Networking Nights", "Eligible": "Yes", "Reason": "Always open"},
            {
                "Event": "CPT Info Sessions",
                "Eligible": "Yes" if cpt_status == "Active" else "No",
                "Reason": "Active CPT" if cpt_status == "Active" else "CPT not active",
            },
        ]

        st.table(results)
